package com.variant.core.schema.parser;

/*
import java.util.List;

import com.variant.core.UserError.Severity;
import com.variant.core.schema.ParserMessage;
import com.variant.core.schema.Schema;

/**
 * Represents the outcome of the XDM schema parsing operation.
 * Returned by {@link com.variant.core.Variant#parseSchema(java.io.InputStream, boolean)}.
 * Host code can obtain information about the outcome of the parsing operation.
 * 
 * @author Igor Urisman
 * @since 0.5
 * /////// No longer public, so we don't need the interface ////////
public interface ParserResponse {
	
	/**
	 * List of all parse messages in order they were emitted.
	 * @return A list of objects of type {@link ParserMessage}.
	 * @since 0.5
	 *
	List<ParserMessage> getMessages();

	/**
	 * Equivalent to <code>!{@link #getMessages()}.isEmpty()</code>.
	 * @return True there are messages of any severity, or false otherwise.
	 * @since 0.5
	 *
	boolean hasMessages();

	/**
	 * List of all parse messages of given severity or higher, in order they were emitted.
	 * @return A list of objects of type {@link ParserMessage}.
	 * @since 0.5
	 *
	List<ParserMessage> getMessages(Severity severity);

	/**
	 * Equivalent to <code>!{@link #getMessages(severity)}.isEmpty()</code>.
	 * @return True there are messages of given severity or higher, false otherwise.
	 * @since 0.5
	 *
	boolean hasMessages(Severity severity);
	
	/**
	 * Parsed schema.
	 * @return {@link Schema} object if no ERROR or FATAL severity message were generated by the parser, or null otherwise.
	 * @since 0.7
	 *
	Schema getSchema();
	
	/**
	 * Source schema.
	 * @return String containing the schema definition, if no ERROR or FATAL severity message were generated by the parser, or null otherwise.
	 * @since 0.7
	 *
	String getSchemaSrc();
}
*/

import static com.variant.core.schema.parser.ParserError.JSON_PARSE;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import com.variant.core.UserError;
import com.variant.core.UserError.Severity;
import com.variant.core.schema.ParserMessage;
import com.variant.core.schema.Schema;
import com.variant.core.schema.impl.SchemaImpl;

public class ParserResponse {

	private ArrayList<ParserMessage> messages = new ArrayList<ParserMessage>();
	private SchemaImpl schema = new SchemaImpl();
	private String schemaSrc = null;
	private ParserListener parserListener = null;
	
	/**
	 * Private common part of adding the message which posts the parser listener, if any.
	 * @param message
	 */
	private void addMessageCommon(ParserMessage message) {
		messages.add(message);
		if (parserListener != null) parserListener.messageAdded(message);
	}
	
	public ParserResponse() {}
	
	//---------------------------------------------------------------------------------------------//
	//                                          PUBLIC                                             //
	//---------------------------------------------------------------------------------------------//

	/**
	 * @return
	 */
	public List<ParserMessage> getMessages() {
		return Collections.unmodifiableList(messages);
	}

	public boolean hasMessages() {
		return ! messages.isEmpty();
	}

	/**
	 * @return
	 */
	public List<ParserMessage> getMessages(Severity severity) {
		ArrayList<ParserMessage> response = new ArrayList<ParserMessage>();
		for (ParserMessage msg: messages) {
			if (msg.getSeverity().greaterOrEqual(severity)) response.add(msg);
		}
		return Collections.unmodifiableList(response);
	}

	public boolean hasMessages(Severity severity) {
		return ! getMessages(severity).isEmpty();
	}

	public Schema getSchema() {
		return schema;
	}

	public String getSchemaSrc() {
		return schemaSrc;
	}

	/**
	 * Add externally generated message.
	 */
    public void addMessage(Severity severity, String message) {
		ParserMessage result = new ParserMessageImpl(new ParserHookError(severity, message));
		addMessageCommon(result);
	}

	/**
	 * Add internally generated messsage
	 */
	public ParserMessage addMessage(ParserError error, int line, int column, String...args) {
		
		ParserMessage result;
		
		if (error.equals(JSON_PARSE)) {
			result = new SyntaxError(error, line, column, args);
		}
		else {
			result = new ParserMessageImpl(error, line, column, args);
		}
		addMessageCommon(result);
		return result;
	}

	/**
	 * 
	 * @param error
	 */
	public ParserMessage addMessage(UserError error, String...args) {
		ParserMessage result = new ParserMessageImpl(error, args);
		addMessageCommon(result);
		return result;
	}

	/**
	 * 
	 * @param schemaSrc
	 */
	public void setSchemaSrc(String schemaSrc) {
		this.schemaSrc = schemaSrc;
	}
	
	/**
	 * Clear the schema in progress, at the end of an unsuccessful parse.
	 */
	public void clearSchema() {
		schema = null;
		schemaSrc = null;
	}
	
	/**
	 * 
	 * @param listener
	 */
	public void setParserListener(ParserListener listener) {
		this.parserListener = listener;
	}
}
