package com.variant.core.schema.parser;

/**
 * Parser Message. Generated by Variant parser at run time and obtainable
 * from {@link ParserResponse}.
 * 
 * @author Igor Urisman
 * @since 0.5
 */
public interface ParserMessage {
	
	/**
	 * The severity of the message.
	 * 
	 * @return An object of type {@link Severity}.
	 * @since 0.5
	 */
	public Severity getSeverity();
	
	/**
	 * The text of the message.
	 * 
	 * @return The text of the message.
	 * @since 0.5
	 */
	public String getText();
	
	/**
	 * Internally generated code of this message.
	 * 
	 * @return Code string.
	 * @since 0.5
	 */
	public String getCode();

	/**
	 * Line number in the source document of the syntax error.
	 * 
	 * @return Line number, if this is a syntax error, or null otherwise.
	 * @since 0.5
	 */
	public Integer getLine();
	
	/**
	 * Column number in the source document of the syntax error.
	 * 
	 * @return Column number if this is a syntax error or null otherwise.
	 * @since 0.5
	 */
	public Integer getColumn();
	
}
