package com.variant.core.schema.parser;

import com.variant.core.exception.Error.Severity;
import com.variant.core.exception.Error;
import com.variant.core.schema.ParserMessage;

/**
 * Parser Message. Generated by Variant parser at run time and obtainable
 * from {@link ParserResponse}.
 * 
 * @author Igor Urisman
 * @since 0.5
 */
public class ParserMessageImpl implements ParserMessage {
	
	private Severity severity;
	private String message;
	private String code;	
	private Integer line = null, column = null;

	/**
	 * 
	 * @param error
	 * @param args
	 * @since 0.5
	 */
	 public ParserMessageImpl(Error error, String...args) {
		severity = error.severity;
		message = String.format(error.format, (Object[]) args);
		code = error.code;
	}

	/**
	 * 
	 * @param error
	 * @param line
	 * @param column
	 * @param args
	 * @since 0.5
	 */
	public ParserMessageImpl(Error error, int line, int column, String...args) {
		this(error, args);
		this.line = line;
		this.column = column;
	}

	/**
	 * User defined errors do not use templates.
	 * @param template
	 * @param args
	 * @since 0.5
	 */
	public ParserMessageImpl(Severity severity, String message) {
		this.severity = severity;
		this.message = message;
		code = "USER_DEFINED_MESSAGE";
	}

	//---------------------------------------------------------------------------------------------//
	//                                          PUBLIC                                             //
	//---------------------------------------------------------------------------------------------//

	/**
	 * 
	 * @return
	 * @since 0.5
	 */
	public Severity getSeverity() {
		return severity;
	}

	/**
	 * 
	 * @return
	 * @since 0.5
	 */
	public String getText() {
		return message;
	}
	
	/**
	 * Error code
	 * @return
	 * @since 0.5
	 */
	public String getCode() {
		return code;
	}

	/**
	 * 
	 * @return
	 * @since 0.5
	 */
	public Integer getLine() {
		return line;
	}
	
	/**
	 * 
	 * @return
	 * @since 0.5
	 */
	public Integer getColumn() {
		return column;
	}
	
	//---------------------------------------------------------------------------------------------//
	//                                         PUBLIC EXT                                          //
	//---------------------------------------------------------------------------------------------//
	
	/**
	 * 
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(getSeverity().name()).append(" - [").append(getCode()).append("] ").append(getText());
		if (line != null) result.append(String.format(" @ line %s, column %s", line, column));
		return result.toString();
	}

}
