package com.variant.core.schema.parser;

/**
 * Custom messages generated by hooks.
 * @author Igor
 *
 */
public class ParserHookError extends ParserError {
			
	protected ParserHookError(Severity severity, String message) {
		super(HOOK_MESSAGE.getCode(), severity, HOOK_MESSAGE.asMessage(severity, message));
	}
	
}
