package com.variant.server.controller

import com.variant.core.ServerError._
import com.variant.server.boot.ServerErrorRemote
import com.variant.server.conn.Connection
import com.variant.server.conn.ConnectionStore
import com.variant.server.conn.SessionStore
import javax.inject.Inject
import play.api.Logger
import com.variant.server.api.ServerException
import com.variant.core.util.Constants._
import com.variant.core.ConnectionStatus._
import play.api.mvc.ControllerComponents

//@Singleton -- Is this for non-shared state controllers?
class ConnectionController @Inject() (
      override val connStore: ConnectionStore, 
      override val ssnStore: SessionStore,
      val connectedAction: ConnectedAction,
      val unconnectedAction: UnconnectedAction,
      val cc: ControllerComponents
      ) extends VariantController(connStore, ssnStore, cc)  {
   
   private val logger = Logger(this.getClass)	

   /**
    * POST
    * Open a new connection to a schema by name.
    * The only call that does not have the connection ID header,
    * because it hasn't yet been generated by this call.
    */
   def open(name: String) = unconnectedAction { req =>
      
      getConnId(req) match {
         case None => // Expected
         case Some(cid) => throw new ServerException.Remote(ConnectionIdNotExpected, cid, name)
      }
      
      server.schemata.get(name) match {
        
         case Some(schema) => {
           
            logger.debug("Schema [%s] found".format(name))
            val conn = Connection(schema)
            
            if (connStore.put(conn)) {
               logger.info("Opened connection [%s] to schema [%s]".format(conn.id, name))
               Ok(conn.asJson).withHeaders(HTTP_HEADER_CONN_STATUS -> OPEN.toString())
            }
            else {
               logger.info("Unable to open connection to schema [%s]: connection table is full".format(name))
               ServerErrorRemote(TooManyConnections).asResult()
            }
         }
         case None => {
            logger.debug("Schema [%s] not found".format(name))
            ServerErrorRemote(UnknownSchema).asResult(name)
         }
      }
   }
  
   /**
    * DELETE
    * Close an existing connection.
    */
   def close() = connectedAction { req =>

      val cid = getConnIdOrBust(req)
      val conn = connStore.closeOrBust(cid)
      logger.info("Closed connection [%s] to schema [%s]".format(cid, conn.schema.getName))
      Ok.withHeaders(HTTP_HEADER_CONN_STATUS -> CLOSED_BY_CLIENT.toString())
   }
   
   /*******************************\
    * GET
    * Check-alive ping. NOT CURRENTLY USED.
    * If connection has been closed by the server return
    *   Status: 400
    * Content: 702 Unknown Connection
    * If connection is alive, no content is returned:
    *   Status: 200
    *   Content: none
    *
   def ping(cid: String) = variantAction {
      //val conn = connStore.getOrBust(cid)
      //logger.trace(s"Connection [${conn.id}] found")
      NotImplemented
   }
   ********************************/
}
