package com.variant.server.controller

import com.variant.core.ServerError._
import com.variant.server.boot.ServerErrorRemote
import com.variant.server.conn.Connection
import com.variant.server.conn.ConnectionStore
import com.variant.server.conn.SessionStore
import javax.inject.Inject
import play.api.Logger
import com.variant.server.api.ServerException
import com.variant.core.util.Constants

//@Singleton -- Is this for non-shared state controllers?
class ConnectionController @Inject() (
      override val connStore: ConnectionStore, 
      override val ssnStore: SessionStore
      ) extends VariantController  {
   
   private val logger = Logger(this.getClass)	

   /**
    * POST
    * Open a new connection to a schema by name.
    * The only call that does not have the connection ID header,
    * because it hasn't yet been generated by this call.
    */
   def open(name: String) = VariantAction { req =>

      val connId = req.headers.get(Constants.HTTP_HEADER_CONNID)
      
      if (connId.isDefined) 
         throw new ServerException.Remote(ConnectionIdNotExpected, connId.get, name)
      
      server.schemata.get(name) match {
        
         case Some(schema) => {
           
            logger.debug("Schema [%s] found".format(name))
            val conn = Connection(schema)
            
            if (connStore.put(conn)) {
               logger.info("Opened connection [%s] to schema [%s]".format(conn.id, name))
               Ok(conn.asJson)
            }
            else {
               logger.info("Unable to open connection to schema [%s]: connection table is full".format(name))
               ServerErrorRemote(TooManyConnections).asResult()
            }
         }
         case None => {
            logger.debug("Schema [%s] not found".format(name))
            ServerErrorRemote(UnknownSchema).asResult(name)
         }
      }
   }
  
   /**
    * DELETE
    * Close an existing connection.
    */
   def close() = VariantAction { req =>

      val connId = getConnectionOrBust(req)
      val conn = connStore.closeOrBust(connId)
      logger.info("Closed connection [%s] to schema [%s]".format(connId, conn.schema.getName))
      Ok
   }
   
   /**
    * GET
    * Check-alive ping.
    * If connection has been closed by the server return
    *   Status: 400
    * Content: 702 Unknown Connection
    * If connection is alive, no content is returned:
    *   Status: 200
    *   Content: none
    */
   def ping(cid: String) = VariantAction {
      val conn = connStore.getOrBust(cid)
      logger.trace(s"Connection [${conn.id}] found")
      Ok
   }

}
